ORG 0H

INIT_PORTS:
    MOV P0, #0FFH
    MOV P1, #0FFH
    MOV P2, #0FFH
    MOV P3, #0FFH
    RET

INIT_LCD:
    MOV P2, #038H
    CALL COMMAND_DELAY
    MOV P2, #00CH
    CALL COMMAND_DELAY
    MOV P2, #006H
    CALL COMMAND_DELAY
    MOV P2, #001H
    CALL COMMAND_DELAY
    RET

COMMAND_DELAY:
    MOV R2, #0FFH
COMMAND_DELAY_LOOP:
    NOP
    DJNZ R2, COMMAND_DELAY_LOOP
    RET

CLEAR_LCD:
    CLR P3.4
    CLR P3.5
    SETB P3.6
    MOV P2, #01H
    CALL COMMAND_DELAY
    CLR P3.6
    RET

DISPLAY_CHAR_LCD:
    SETB P3.4
    CLR P3.5
    SETB P3.6
    MOV P2, A
    CALL COMMAND_DELAY
    CLR P3.6
    RET

DISPLAY_STRING_LCD:
    MOV A, #00H
DISPLAY_STRING_LOOP:
    MOVC A, @A+DPTR   
    JZ DISPLAY_STRING_DONE
    CALL DISPLAY_CHAR_LCD
    INC DPTR
    JMP DISPLAY_STRING_LOOP
DISPLAY_STRING_DONE:
    RET

ROTATE_MOTOR:
    SETB P3.0
    CALL MOTOR_DELAY
    CLR P3.0
    SETB P3.1
    CALL MOTOR_DELAY
    CLR P3.1
    RET

MOTOR_DELAY:
    MOV R3, #0FFH          
OUTER_LOOP:
    MOV R2, #0FFH          
INNER_LOOP:
    CALL COMMAND_DELAY      
    DJNZ R2, INNER_LOOP     
    DJNZ R3, OUTER_LOOP     
    RET

CHECK_PASSWORD:
    MOV A, R0
    CJNE A, #56H, WRONG_PASSWORD
    MOV A, R1
    CJNE A, #78H, WRONG_PASSWORD
    RET

WRONG_PASSWORD:
    CALL CLEAR_LCD
    MOV DPTR, #WRONG_MSG
    CALL DISPLAY_STRING_LCD
    RET

MAIN:
    CALL INIT_PORTS
    CALL INIT_LCD

PASSWORD_ENTRY_LOOP:
    CALL GET_PASSWORD
    CALL CHECK_PASSWORD
    JZ PASSWORD_INCORRECT

    CALL CLEAR_LCD
    MOV DPTR, #DOOR_OPEN_MSG
    CALL DISPLAY_STRING_LCD
    CALL ROTATE_MOTOR
    JMP MAIN

PASSWORD_INCORRECT:
    CALL CLEAR_LCD
    MOV DPTR, #WRONG_MSG
    CALL DISPLAY_STRING_LCD
    JMP PASSWORD_ENTRY_LOOP

GET_PASSWORD:
    CALL READ_KEYPAD
    MOV R0, A
    CALL READ_KEYPAD
    MOV R1, A
    RET

READ_KEYPAD:
    MOV P1, #0F0H  
SCAN_COLUMN:
    CLR P1.0       
    MOV A, P1
    ANL A, #0F0H   
    JNZ CHECK_COL2 
    MOV A, #31H    
    RET

CHECK_COL2:
    SETB P1.0
    CLR P1.1
    MOV A, P1
    ANL A, #0F0H
    JNZ CHECK_COL3
    MOV A, #32H    
    RET

CHECK_COL3:
    SETB P1.1
    CLR P1.2
    MOV A, P1
    ANL A, #0F0H
    JNZ CHECK_COL4
    MOV A, #33H    
    RET

CHECK_COL4:
    SETB P1.2
    CLR P1.3
    MOV A, P1
    ANL A, #0F0H
    JNZ READ_KEYPAD
    MOV A, #34H    
    RET

DOOR_OPEN_MSG: DB 'Door Opening', 0
WRONG_MSG: DB 'Wrong Password', 0

END
