ORG 0H

INIT_PORTS:
    MOV P0, #0FFH
    MOV P1, #0FFH
    MOV P2, #0FFH
    MOV P3, #0FFH
    RET

INIT_LCD:
    MOV P2, #038H
    CALL COMMAND_DELAY
    MOV P2, #00CH
    CALL COMMAND_DELAY
    MOV P2, #006H
    CALL COMMAND_DELAY
    MOV P2, #001H
    CALL COMMAND_DELAY
    RET

COMMAND_DELAY:
    MOV R2, #0FFH
COMMAND_DELAY_LOOP:
    NOP
    DJNZ R2, COMMAND_DELAY_LOOP
    RET

CLEAR_LCD:
    CLR P0.0
    CLR P0.1
    SETB P0.2
    MOV P2, #01H
    CALL COMMAND_DELAY
    CLR P0.2
    RET

DISPLAY_CHAR_LCD:
    SETB P0.0
    CLR P0.1
    SETB P0.2
    MOV P2, A
    CALL COMMAND_DELAY
    CLR P0.2
    RET

DISPLAY_STRING_LCD:
    MOV R2, #00H
DISPLAY_STRING_LOOP:
    MOV A, @R2
    JZ DISPLAY_STRING_DONE
    CALL DISPLAY_CHAR_LCD
    INC R2
    JMP DISPLAY_STRING_LOOP
DISPLAY_STRING_DONE:
    RET

ROTATE_MOTOR:
    MOV P3, #01H
    CALL MOTOR_DELAY
    MOV P3, #02H
    CALL MOTOR_DELAY
    MOV P3, #00H
    RET

MOTOR_DELAY:
    MOV R2, #0C8H
MOTOR_DELAY_LOOP:
    CALL COMMAND_DELAY
    DJNZ R2, MOTOR_DELAY_LOOP
    RET

CHECK_PASSWORD:
    MOV A, R0
    CJNE A, #56H, WRONG_PASSWORD
    MOV A, R1
    CJNE A, #78H, WRONG_PASSWORD
    RET

WRONG_PASSWORD:
    CALL CLEAR_LCD
    MOV DPTR, #WRONG_MSG
    CALL DISPLAY_STRING_LCD
    RET

MAIN:
    CALL INIT_PORTS
    CALL INIT_LCD

PASSWORD_ENTRY_LOOP:
    CALL GET_PASSWORD
    CALL CHECK_PASSWORD
    JZ PASSWORD_INCORRECT

    CALL CLEAR_LCD
    MOV DPTR, #DOOR_OPEN_MSG
    CALL DISPLAY_STRING_LCD
    CALL ROTATE_MOTOR
    JMP MAIN

PASSWORD_INCORRECT:
    CALL CLEAR_LCD
    MOV DPTR, #WRONG_MSG
    CALL DISPLAY_STRING_LCD
    JMP PASSWORD_ENTRY_LOOP

GET_PASSWORD:
    MOV R0, #56H
    MOV R1, #78H
    RET

DOOR_OPEN_MSG: DB 'Door Opening', 0
WRONG_MSG: DB 'Wrong Password', 0

END
